export enum ActionTypes {
  ADD_NEW_ITEM_IN_CART = 'ADD_NEW_ITEM_IN_CART',
  ADD_ITEM_IF_ALREADY_EXISTS_THIS_IN_CART = 'ADD_ITEM_IF_ALREADY_EXISTS_THIS_IN_CART',
  ADD_ONE_AMOUNT_OF_ITEM = 'ADD_ONE_AMOUNT_OF_ITEM',
  REMOVE_ONE_AMOUNT_OF_ITEM = 'REMOVE_ONE_AMOUNT_OF_ITEM',
  REMOVE_ITEM_OF_CART = 'REMOVE_ITEM_OF_CART',
  ADD_ITEM_ON_DROP = 'ADD_ITEM_ON_DROP',
}
